const API_AUTH_URL = process.env.NEXT_PUBLIC_AUTH_API_URL;
const API_ADMIN_URL=process.env.NEXT_PUBLIC_ADMIN_API_URL;
const API_USER_URL=process.env.NEXT_PUBLIC_USER_API_URL;

export { API_AUTH_URL,API_ADMIN_URL,API_USER_URL }